---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hjs.
--- DateTime: 2019/4/10 10:05
---

---@class AddDiamondsAction:BaseFrameAction
local AddDiamondsAction = class(BaseFrameAction)

---@return AddDiamondsAction
function AddDiamondsAction:Create(params, finishCallback)
    local action = AddDiamondsAction.new(params, finishCallback)
    return action
end

function AddDiamondsAction:ctor(params, finishCallback)
    self.name = "AddDiamondsAction"

    self.delay = params.delay or 0
    self.prefab = G_EFFECT_BUILDING_REWARD_PTC
    self.position = params.position or Camera.main:ScreenToWorldPoint(Vector3(Screen.width * 0.5, Screen.height * 0.5, 0))
    self.count = params.count or 0

    self.isFinished = false
    self.started = false

    self.finishCallback = finishCallback
end

function AddDiamondsAction:Awake()
    local function start()
        local function onLoadFinish()
            AppServices.DiamondLogic:GetView():ShowEnterAnim()
            AppServices.DiamondLogic:GetView():SetInteractable(false)
            AppServices.User:AddItem(ItemId.DIAMOND, self.count, "AddDiamondsAction")
            local startPos = self.position
            local go_ptc = BResource.InstantiateFromAssetName(self.prefab)
            go_ptc:SetPosition(startPos)
            WaitExtension.SetTimeout(function()
                AppServices.DiamondLogic:GetView():OnHit()
                AppServices.DiamondLogic:RefreshDiamondNumberWithAnimation()

                if PanelManager.isShowingAnyPanel() then
                    WaitExtension.SetTimeout(
                            function()
                                AppServices.DiamondLogic:GetView():ShowExitAnim()
                                AppServices.DiamondLogic:GetView():SetInteractable(true)
                            end, 0.5)
                end

                Runtime.InvokeCbk(self.finishCallback)

                self.isFinished = true
            end, 1)

            Runtime.CSDestroy(go_ptc, 1.5)
        end

        AssetLoaderUtil.LoadAssets({ self.prefab }, onLoadFinish)
    end

    if self.delay > 0 then
        WaitExtension.SetTimeout(start, self.delay)
    else
        start()
    end
end

function AddDiamondsAction:Update()
    if not self.started then
        self.started = true
        self:Awake()
    end
end

function AddDiamondsAction:Reset()
    self.started = false
    self.isFinished = false
end

return AddDiamondsAction