---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hjs.
--- DateTime: 2019/4/3 11:47
---

---@class DoShakeCameraAction:BaseFrameAction
local DoShakeCameraAction = class(BaseFrameAction, "AttachAction")

function DoShakeCameraAction:Create(params, finishCallback)
    local instance = DoShakeCameraAction.new(params, finishCallback)
    return instance
end

function DoShakeCameraAction:ctor(params, finishCallback)
    self.name = "DoShakeCameraAction"
    self.finishCallback = finishCallback
    self.started = false
    self.isFinished = false
    self.params = params
end

function DoShakeCameraAction:Awake()
    local duration = self.params.duration or 1
    local strength = self.params.strength or 0.05
    local vibrato = self.params.vibrato or 15
    local randomness = self.params.randomness or 30
    local fadeOut = self.params.fadeOut ~= nil
    XGE.TweenExtension.DoShakeCamera(duration, strength, vibrato, randomness, fadeOut,
            function()
                --self.isFinished = true
                --Runtime.InvokeCbk(self.finishCallback)
            end)
    -- 防止Tween被杀掉
    WaitExtension.SetTimeout(function()
        self.isFinished = true
    end, duration)
end

function DoShakeCameraAction:Update()
    if not self.started then
        self.started = true
        self:Awake()
    end
end

function DoShakeCameraAction:Reset()
    self.started = false
    self.isFinished = false
end

return DoShakeCameraAction