---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/5/31 22:55
---

local Base = require("Game.System.Gift.GiftPrecondition.GiftPreconditionBase")
---@class GiftPreconditionTriggerGift : GiftPreConditionBase
local GiftPreconditionTriggerGift = class(Base, "GiftPreconditionTriggerGift")

function GiftPreconditionTriggerGift:ctor(checkGiftID)
    self.checkGiftID = checkGiftID
end

function GiftPreconditionTriggerGift:Check()
    local ret = AppServices.GiftManager:IsTriggerGift(self.checkGiftID)
    console.dk(self.checkGiftID, "礼包是否触发：", ret) --@DEL
    return ret
end

return GiftPreconditionTriggerGift