---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/5/31 18:03
---

local Base = require("Game.System.Gift.GiftPrecondition.GiftPreconditionBase")
---@class GiftPreconditionAND : GiftPreConditionBase
local GiftPreconditionAND = class(Base, "GiftPreconditionAND")

function GiftPreconditionAND:ctor(preconditionAry)
    self.preconditionAry = preconditionAry
end

function GiftPreconditionAND:Check()
    local log = "" --@DEL
    for _, v in ipairs(self.preconditionAry) do
        local ret = v:Check()
        log = log .. tostring(ret) .. ", " --@DEL
        if not ret then
            console.dk("AND", log) --@DEL
            return false
        end
    end
    console.dk("AND", log) --@DEL
    return true
end

return GiftPreconditionAND