---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/5/31 17:29
---

local Base = require("Game.System.Gift.GiftPrecondition.GiftPreconditionBase")
---@class GiftPreconditionOR : GiftPreConditionBase
local GiftPreconditionOR = class(Base, "GiftPreconditionOR")

function GiftPreconditionOR:ctor(preconditionAry)
    self.preconditionAry = preconditionAry
end

function GiftPreconditionOR:Check()
    local log = "" --@DEL
    for _, v in ipairs(self.preconditionAry) do
        local ret = v:Check()
        log = log .. tostring(ret) .. ", " --@DEL
        if ret then
            console.dk("OR", log) --@DEL
            return true
        end
    end
    console.dk("OR", log) --@DEL
    return false
end

return GiftPreconditionOR