---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/2/28 18:00
---

UserInputType = {
    none = 0,
    click = 1,
    drag = 2,
    press = 3,
    zoom = 4,
    clickGround= 5,
    clickObstacle = 6,
    clickCreature = 7,
    mouseDown = 8,
    mouseUp = 9,
    clickEntity = 10,
    clickTips = 11,
}
---@class UserInput
UserInput = {}

local listeners
local delta
local position
local castList

function UserInput.getPosition()
    return position
end
function UserInput.setPosition(point)
    position = point
end

function UserInput.getDelta()
    return delta
end
function UserInput.setDelta(deltaPosition)
    delta = deltaPosition
end

function UserInput.setCastList(list)
    castList = list
end

function UserInput.getCastList()
    return castList
end

function UserInput.onTrigger(eventType)
    if listeners then
        if listeners[eventType] then
            for handler, callback in pairs(listeners[eventType]) do
                Runtime.InvokeCbk(callback, handler)
            end
        end
    end
end

---@param type UserInputType
---@param callback function<param>
function UserInput.registerListener(handler, type, callback)
    if not listeners then
        listeners = {}
    end
    if not listeners[type] then
        listeners[type] = {}
    end
    listeners[type][handler] = callback
end

function UserInput.removeListener(handler, type)
    if not listeners then
        return
    end
    if type then
        if not listeners[type] then
            return
        end
        if not listeners[type][handler] then
            return
        end
        listeners[type][handler] = nil
    else
        for eventType, ls in pairs(listeners) do
            if ls[handler] then
                ls[handler] = nil
            end
        end
    end
end

function UserInput.Clear()
    delta = nil
    position = nil
    castList = nil
end
