---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/27 17:44
local base = require 'UI.Mail.MailDetailPanel.View.UI.Template.MailTemplateBase'
---@class MailTemplateNoPic:MailTemplateBase
local MailTemplateNoPic = class(base, 'MailTemplateNoPic')

return MailTemplateNoPic