return {
    Fly_CostCoin = "Prefab/UI/Common/FlyCostCoin.prefab",
    Fly_CostDiamond = "Prefab/UI/Common/FlyCostDiamond.prefab",
    Fly_CostHeart = "Prefab/UI/Common/FlyCostHeart.prefab",
    FIREWORKS = "Prefab/UI/UIEffect/UIEffect_firework_loop.prefab",
    FIREWORK = "Prefab/UI/UIEffect/UIEffect_firework.prefab",
    Fly_CoinTrail = "Prefab/UI/UIEffect/Jinbi_trail.prefab",
    Fly_DiamondTrail = "Prefab/UI/UIEffect/Zuanshi_trail.prefab",
    FlyDiamondHit = "Prefab/UI/UIEffect/Zuanshi_first_boom.prefab",
    FlyCoinHit = "Prefab/UI/UIEffect/Jinbi_first_boom.prefab",
    FlyCoinHit2 = "Prefab/UI/UIEffect/Jinbi_chixu_boom.prefab",
    FloaterClick = "Prefab/UI/UIEffect/E_receive.prefab",
    UnlockIcon = "Prefab/UI/UIEffect/E_UI_Unlocking.prefab",
    Fly_TimeOrderTrail = "Prefab/UI/TimeOrder/E_TimeOrder_trail.prefab",
}