---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/27 17:44

local base = require "UI.Mail.MailDetailPanel.View.UI.Template.MailTemplateBase"

---@class MailTemplatePic:MailTemplateBase
local t = class(base, "MailTemplatePic")

function t:AfterInitComponent()
    self.img_Picture = find_component(self.gameObject, "img_pic", CS.RemotePicture)
end

---@param data Mail
function t:SetData(data)
    self.super.SetData(self, data)
    self:SetPicture(self.data.picUrl)
end

function t:SetPicture(url)
    if string.isEmpty(url) then

        return
    end
    self.img_Picture.gameObject:SetActive(false)
    local fileName = CS.System.IO.Path.GetFileNameWithoutExtension(url)
    if string.isEmpty(fileName) then
        console.error("img url error , url  = " .. url)
    else
        self.img_Picture:Refresh(fileName, url)
    end
    self.img_Picture.gameObject:SetActive(true)
end
return t
