---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/4/16 18:24
---
--- 区域矩形块
---     位置信息: 位置, 大小
---     解锁状态
---

local kRectMeta = {
    id = "id",
    minX = "x",
    minZ = "z",
    sizeX = "xSize",
    sizeZ = "zSize",
    open = "open"
}

local offset = Vector3(-0.5, 0, -0.5)
---@class Rect @区块信息
local Rect = class(nil, "Rect")

function Rect:ctor(rectMeta)
    ---@type RegionMeta @源数据
    self.meta = rectMeta
    self.id = self.meta[kRectMeta.id]
    self.xMin = self.meta[kRectMeta.minX]
    self.zMin = self.meta[kRectMeta.minZ]
    self.xSize = self.meta[kRectMeta.sizeX]
    self.zSize = self.meta[kRectMeta.sizeZ]
    self.open = self.meta[kRectMeta.open]

    self.openColor = Color(0.1, 1, 0.1, 0.6)
    self.closeColor = Color(1, 0.1, 0.1, 0.6)
end

function Rect:Init(open)
    self.open = open

    local map = App.scene.mapManager --@DEL
    ---@private
    self.size = Vector3(self.xSize, 0, self.zSize) --@DEL
    ---@private
    local min = map:ToWorld(self.xMin, self.zMin) --@DEL
    local max = map:ToWorld(self.xMin + self.xSize - 1, self.zMin + self.zSize - 1) --@DEL
    self.center = (min + max) * 0.5 + offset --@DEL
    ---@private
    self.size = self.size - Vector3(0.1, 0, 0.1) --@DEL
end

function Rect:ContainsGrid(x, z)
    if x < self.xMin then
        return false
    end
    if x > self.xMin + self.xSize - 1 then
        return false
    end
    if z < self.zMin then
        return false
    end
    if z > self.zMin + self.zSize - 1 then
        return false
    end
    return true
end

function Rect:DrawGizmos()
    if CS.GizmosUtil.showRect then
        local Gizmos = CS.UnityEngine.Gizmos
        
        local color
        if self.open then
            color = self.openColor
        else
            color = self.closeColor
        end

        Gizmos.color = color
        Gizmos.DrawWireCube(self.center, self.size)
    end
end
return Rect
