---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/26 16:38
require "UI.Components.HomeSceneTopIconBase"
---@class MailButton:HomeSceneTopIconBase
local MailButton = class(HomeSceneTopIconBase, "MailButton")
function MailButton:Create()
    local gameObject = BResource.InstantiateFromAssetName(CONST.ASSETS.G_UI_HOMESCENE_MAIL)
    return MailButton:CreateWithGameObject(gameObject)
end

function MailButton:CreateWithGameObject(gameObject)
    local instance = MailButton.new()
    instance:InitWithGameObject(gameObject)
    return instance
end

function MailButton:InitWithGameObject(gameObject)
    self.gameObject = gameObject
    self:InitComponent()
    self:BindEvent()
end

-- function MailButton:ctor()
--     local gameObject = BResource.InstantiateFromAssetName(CONST.ASSETS.G_UI_HOMESCENE_MAIL)
--     if Runtime.CSValid(gameObject) then
--         self.gameObject = gameObject
--         self:InitComponent()
--         self:BindEvent()
--     end
-- end

function MailButton:InitComponent()
    self.redDot = find_component(self.gameObject, "img_icon/img_reddot")
end

function MailButton:BindEvent()
    Util.UGUI_AddButtonListener(
        self.gameObject,
        function()
            local widgetsMenu = App.scene:GetWidget(CONST.MAINUI.ICONS.HRWidgetsMenu)
            --widgetsMenu:OnClickMenuBtn()
            widgetsMenu:ResetToggle()
            console.trace("mail MailButton clicked") --@DEL
            PanelManager.showPanel(GlobalPanelEnum.MailMainPanel)
        end, {noAudio = true}
    )

    self:RefreshRedDot()
end

function MailButton:RefreshRedDot()
    if Runtime.CSValid(self.redDot) then
        self:InitComponent()
        if Runtime.CSValid(self.redDot) then
            local hasRedDot = AppServices.MailManager:NeedShowRedDot()
            self.redDot.gameObject:SetActive(hasRedDot)
            local widgetsMenu = App.scene:GetWidget(CONST.MAINUI.ICONS.HRWidgetsMenu)
            widgetsMenu:ForceViewOutItem(CONST.MAINUI.ICONS.MailButton,hasRedDot)
        end
    end
end

return MailButton
