---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/7 18:17
---
---@class ScheduleLoopCall
ScheduleLoopCall = class(nil, "ScheduleLoopCall")

function ScheduleLoopCall.Create(callback, interval, args)
    interval = interval or 0
    local schedule = ScheduleLoopCall.new(callback, args, interval)
    return schedule
end

function ScheduleLoopCall:ctor(callback, args, interval)
    self.callback = callback
    self.args = args
    self.interval = interval
    self.alive = true

    self.scheduleId =
        WaitExtension.InvokeRepeating(
        function(deltaTime)
            if self.alive then
                Runtime.InvokeCbk(self.callback, self.args, deltaTime)
            end
        end,
        0,
        interval
    )
end

function ScheduleLoopCall:Destroy()
    if self.scheduleId then
        WaitExtension.CancelTimeout(self.scheduleId)
    end

    self.scheduleId = nil
    self.callback = nil
    self.args = nil
    self.alive = nil
end
