---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/30 18:55
---

---@class ScheduleBase
ScheduleBase = class(nil, "ScheduleBase")

function ScheduleBase.Create(callback, delay, args)
    delay = delay or 0
    if delay <= 0 then
        --如果延迟为0, 立刻调用.
        Runtime.InvokeCbk(callback, args)
    else
        local schedule = ScheduleBase.new(callback, args, delay)
        return schedule
    end
end

function ScheduleBase:ctor(callback, args, delay)
    self.callback = callback
    self.args = args
    self.delay = delay
    self.alive = true

    self.schedule =
        WaitExtension.SetTimeout(
        function()
            if self.alive then
                Runtime.InvokeCbk(self.callback, self.args)
            end
            self:Destroy()
        end,
        delay
    )
end

function ScheduleBase:Reset()
    self.alive = true
    if self.schedule then
        WaitExtension.CancelTimeout(self.schedule)
    end
    self.schedule =
        WaitExtension.SetTimeout(
        function()
            if self.alive then
                Runtime.InvokeCbk(self.callback, self.args)
            end
            self:Destroy()
        end,
        self.delay
    )
end

function ScheduleBase:Destroy()
    if self.schedule then
        WaitExtension.CancelTimeout(self.schedule)
    end

    self.schedule = nil
    self.alive = nil
end
