---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/6/1 16:11
---
---体力折扣buff礼包
local Base = require("Game.System.Gift.GiftInstance.GiftInstanceBase")
---@class GiftInstance_440 : GiftInstanceBase
local GiftInstance_440 = class(Base, "GiftInstance_440")

function GiftInstance_440:ctor(config)
    GiftInstance_440.super.ctor(self, config)
end

function GiftInstance_440:AutoOpenEvent()
    return {}
end

function GiftInstance_440:GetPanelName()
    return "GiftResourcePanel"
end

function GiftInstance_440:GetPopFlag()
    return {}
end

function GiftInstance_440:GetUIConfig()
    local offNum = "0"
    local offPercent = "0"
    if #self.shopConfig.itemIds > 0 then
        local itemCfg = AppServices.Meta:GetItemMeta(self.shopConfig.itemIds[1][1])
        if itemCfg and itemCfg.funcType == 10 then
            local buffId = AppServices.Meta:GetItemFuncParam(self.shopConfig.itemIds[1][1])
            local cof = AppServices.Meta:GetBuffMeta(tostring(buffId))
            if cof then
                local timebuffOffPercent = cof.effectParam[1]
                offNum = tostring(math.floor(100 * timebuffOffPercent))
                offPercent = string.format("%d<size=20>%%</size>", timebuffOffPercent*100)
            end
        end
    end
    return {Localization = {localization_desc = "UI_energy_halving_buff_desc"}, CodeStr = {offNum = offNum, offPercent = offPercent}}
end

return GiftInstance_440