---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/6/1 15:14
---
---棒棒糖礼包3
local Base = require("Game.System.Gift.GiftInstance.GiftInstanceBase")
---@class GiftInstance_452 : GiftInstanceBase
local GiftInstance_452 = class(Base, "GiftInstance_452")

function GiftInstance_452:ctor(config)
    GiftInstance_452.super.ctor(self, config)

    local userGroup = Base.PreconditionUserGroup.new({"7"})
    local trigger450 = Base.PreconditionTriggerGift.new(450)
    local trigger451 = Base.PreconditionTriggerGift.new(451)
    local trigger452 = Base.PreconditionTriggerGift.new(452)
    local firstCheck = Base.PreconditionAND.new({userGroup,     --初始AEO，中R展示5.99档位
                                                 Base.PreconditionNO.new(trigger450),
                                                 Base.PreconditionNO.new(trigger451),
                                                 Base.PreconditionNO.new(trigger452)})
    local Bought452 = Base.PreconditionBoughtGift.new(452, false)  --购买了452档次
    local Bought451 = Base.PreconditionBoughtGift.new(451, true)
    local upCheck = Base.PreconditionAND.new({Bought451, Base.PreconditionNO.new(trigger452)})  --购买了451档位，还没触发过452档位，尝试触发452档位
    self:AddPrecondition(Base.PreconditionOR.new({firstCheck, Bought452, upCheck}))
end

function GiftInstance_452:GetPanelName()
    return "GiftResourcePanel"
end

function GiftInstance_452:AutoOpenEvent()
    return {}
end

function GiftInstance_452:GetUIConfig()
    return {Localization = {localization_title = "UI_gift_key_title", localization_desc = "UI_gift_key_desc", text_buy = "UI_gift_buy"}}
end

return GiftInstance_452