---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/6/1 15:41
---
---金币礼包
local Base = require("Game.System.Gift.GiftInstance.GiftInstanceBase")
---@class GiftInstance_410 : GiftInstanceBase
local GiftInstance_410 = class(Base, "GiftInstance_410")

function GiftInstance_410:ctor(config)
    GiftInstance_410.super.ctor(self, config)

    self:AddPrecondition(Base.PreconditionUserGroup.new({"3", "6", "7"}))
end

function GiftInstance_410:AutoOpenEvent()
    return {}
end

function GiftInstance_410:GetPanelName()
    return "GiftResourcePanel"
end

function GiftInstance_410:GetPopFlag()
    return {}
end

function GiftInstance_410:GetUIConfig()
    return {Localization = {localization_title = "UI_coin_special"}}
end

return GiftInstance_410