<?php
return array(
9103202=>["BuffID"=>9103202,"Sequence"=>1,"Icon"=>"","Description"=>"【海盗船长】水帘","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"effect_ch_Lodumani_skill2_01","NpcDisappearEffect"=>"effect_ch_Lodumani_skill2_02","Class"=>""],
9105202=>["BuffID"=>9105202,"Sequence"=>1,"Icon"=>"","Description"=>"【美国大兵】降移速手雷","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"effect_ch_soldier_loop1","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"effect_ch_soldier_loop1","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"effect_ch_soldier_loop1","NpcDisappearEffect"=>"","Class"=>"SlowGrenade"],
9107202=>["BuffID"=>9107202,"Sequence"=>1,"Icon"=>"","Description"=>"【小女孩】无法变鱼手雷","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"effect_ch_inventor_loop1","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"effect_ch_inventor_loop1","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"effect_ch_inventor_loop1","NpcDisappearEffect"=>"","Class"=>"NinjaSmoke"],
9114202=>["BuffID"=>9114202,"Sequence"=>1,"Icon"=>"","Description"=>"【植物】buff地雷-种 透视","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"","NpcDisappearEffect"=>"","Class"=>"Perspectived"],
9115202=>["BuffID"=>9115202,"Sequence"=>1,"Icon"=>"","Description"=>"【忍者】无法恢复手雷","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"effect_ninja0_release1_buff","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"effect_ninja0_release1_buff","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"effect_ninja0_release1_buff","NpcDisappearEffect"=>"","Class"=>"NinjaSmoke"],
9104301=>["BuffID"=>9104301,"Sequence"=>1,"Icon"=>"","Description"=>"【宠物驾驶机甲】吸收伤害值护盾","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"","NpcDisappearEffect"=>"","Class"=>""],
9106301=>["BuffID"=>9106301,"Sequence"=>1,"Icon"=>"","Description"=>"【外星人】无敌屏障","DisplayMethod"=>1,"DummyPoint"=>270,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"effect_aliengirl_skill2_buff","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"effect_aliengirl_skill2_buff","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"effect_aliengirl_skill2_buff","NpcDisappearEffect"=>"effect_aliengirl_skill2_release","Class"=>"InvincibleBarrier"],
9107301=>["BuffID"=>9107301,"Sequence"=>1,"Icon"=>"","Description"=>"【小女孩】Buff效果：自身中心有一个圆形护盾，可以抵挡敌方子弹。不能抵挡爆炸的范围伤害，护盾随着自身移动。","DisplayMethod"=>1,"DummyPoint"=>0,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"effect_ch_inventor_loop2","HumanDisappearEffect"=>"effect_ch_inventor_end2","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"effect_ch_inventor_loop2","FishDisappearEffect"=>"effect_ch_inventor_end2","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"effect_ch_inventor_loop2","NpcDisappearEffect"=>"effect_ch_inventor_end2","Class"=>"NormalShield"],
9109301=>["BuffID"=>9109301,"Sequence"=>1,"Icon"=>"","Description"=>"【亚马逊战士】透视","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"","NpcDisappearEffect"=>"","Class"=>""],
9113301=>["BuffID"=>9113301,"Sequence"=>1,"Icon"=>"","Description"=>"【堆叠小怪】buff：自身为中心的AOE周期伤害，移动速度略加快。周期性向四面八方射击子弹进行喷涂。","DisplayMethod"=>1,"DummyPoint"=>20,"HumanOffsetX"=>0,"HumanOffsetY"=>0,"HumanOffsetZ"=>0,"HumanEffect"=>"","HumanDisappearEffect"=>"","FishOffsetX"=>0,"FishOffsetY"=>0,"FishOffsetZ"=>0,"FishEffect"=>"","FishDisappearEffect"=>"","NpcOffsetX"=>0,"NpcOffsetY"=>0,"NpcOffsetZ"=>0,"NpcEffect"=>"","NpcDisappearEffect"=>"","Class"=>""],
);
?>