<?php
return array(
1=>["ID"=>1,"Desc"=>"哨站任务1弹窗【废弃】","Path"=>"UIRoot/MainLayer/UIOutpostView/Panel/LeftMiddle/Task_0"],
2=>["ID"=>2,"Desc"=>"哨站任务1弹窗【废弃】","Path"=>"UIRoot/PopUpLayer/UIOutPostTaskPanelPopUpView/Panel/img_Bg/Content/img_InfoBg"],
3=>["ID"=>3,"Desc"=>"哨站左下角挑战关卡按钮","Path"=>"UIRoot/MainLayer/UIOutpostView/Panel/LeftDown/img_btnLevelSelection/btn_LevelSelectionView/icon"],
4=>["ID"=>4,"Desc"=>"关卡列表中，关卡100区域","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_0/NormalLevelBtn(Clone)/btn_Level"],
5=>["ID"=>5,"Desc"=>"关卡列表中，关卡102区域","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_1/NormalLevelBtn(Clone)/btn_Level"],
6=>["ID"=>6,"Desc"=>"关卡列表中，关卡103区域","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_2/NormalLevelBtn(Clone)/btn_Level"],
7=>["ID"=>7,"Desc"=>"关卡信息界面，挑战按钮","Path"=>"UIRoot/NormalLayer/UILevelMsgView/Panel/Down/btn_Begin"],
8=>["ID"=>8,"Desc"=>"哨站界面返回按钮","Path"=>"UIRoot/MainLayer/UIOutpostView/Panel/RightDown/img_btnWorldMap/btn_ToWorldMap"],
9=>["ID"=>9,"Desc"=>"世界地图中哨站奖励区域【包括星星和倒计时时间】","Path"=>"UIRoot/MainLayer/UIWorldMapView/Panel/OutPostReward_0/BG/ProgressBar/CountDownPanel/IconObj/img_Icon"],
10=>["ID"=>10,"Desc"=>"前往家园按钮","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/img_btnHomaland/btn_Homeland"],
11=>["ID"=>11,"Desc"=>"关卡主UI，任务目标区域","Path"=>"UIRoot/NormalLayer/UILevelView/Panel/UpMiddle/img_Bg"],
12=>["ID"=>12,"Desc"=>"","Path"=>""],
13=>["ID"=>13,"Desc"=>"","Path"=>""],
14=>["ID"=>14,"Desc"=>"家园商店按钮","Path"=>"UIRoot/MainLayer/UIHomelandView/Panel/Content_RB/btn_Shop"],
15=>["ID"=>15,"Desc"=>"关卡任务之星按钮，任一","Path"=>"UIRoot/MainLayer/UITaskView/Panel/LeftMiddle/Task_0"],
16=>["ID"=>16,"Desc"=>"屏幕锁定按钮","Path"=>"UIRoot/NormalLayer/UILevelView/Panel/RightDown/LockCamera/btn_Lock"],
17=>["ID"=>17,"Desc"=>"家园任务区域","Path"=>"UIRoot/MainLayer/UITaskView/Panel/LeftMiddle/Task_0"],
18=>["ID"=>18,"Desc"=>"商店资源页签","Path"=>"UIRoot/NormalLayer/UIShopView_new/Panel/TogglePanel/Viewport/Content/TabItem_4"],
19=>["ID"=>19,"Desc"=>"金币库道具11901","Path"=>"UIRoot/NormalLayer/UIShopView_new/Panel/TabScrollPanel_6/Viewport/Content/7001"],
20=>["ID"=>20,"Desc"=>"家园返回哨站按钮","Path"=>"UIRoot/MainLayer/UIHomelandView/Panel/RightMiddle/btn_Map/icon"],
21=>["ID"=>21,"Desc"=>"哨站1区域","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_0"],
22=>["ID"=>22,"Desc"=>"图书馆道具12001（原石）","Path"=>"UIRoot/NormalLayer/UIShopView_new/Panel/TabScrollPanel_6/Viewport/Content/7006"],
23=>["ID"=>23,"Desc"=>"英雄升级页签按钮","Path"=>"UIRoot/NormalLayer/UIHeroView/Panel/Hero/Panels/DetailsPanel/Viewport/Content/Part2/ShowUpgrade"],
24=>["ID"=>24,"Desc"=>"英雄技能区域","Path"=>"UIRoot/NormalLayer/UIHeroView/Panel/Hero/Panels/DetailsPanel/Viewport/Content/Part3"],
25=>["ID"=>25,"Desc"=>"","Path"=>""],
26=>["ID"=>26,"Desc"=>"订单内容区域","Path"=>"UIRoot/NormalLayer/UIHeroView/Panel/Upgrade/Upgrade/Content/Panel/Receipts/Scroll View/Viewport/Content"],
27=>["ID"=>27,"Desc"=>"选关界面全屏关闭按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/BG"],
28=>["ID"=>28,"Desc"=>"UI宝箱按钮","Path"=>"UIRoot/MainLayer/UIEpitaphBarView/Panel/EpitaphView/EpitaphViews"],
29=>["ID"=>29,"Desc"=>"UI宝箱界面宝箱1开启按钮","Path"=>"UIRoot/NormalLayer/UIEpitaphView/Panel/Down/EpitaphItem_0/img_Bg/ItemBtns/Three/btn_UnLocked"],
30=>["ID"=>30,"Desc"=>"祭坛信息“操作按钮”","Path"=>"UIRoot/MainLayer/UIDetailsBarView/Panel/img_Mask/img_FlexBg/BtnContent/btn_Update"],
31=>["ID"=>31,"Desc"=>"关卡列表中，关卡104按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_3/NormalLevelBtn(Clone)/btn_Level"],
32=>["ID"=>32,"Desc"=>"关卡列表中，关卡105按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_4/NormalLevelBtn(Clone)/btn_Level"],
33=>["ID"=>33,"Desc"=>"关卡列表中，关卡106按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_5/NormalLevelBtn(Clone)/btn_Level"],
34=>["ID"=>34,"Desc"=>"时间宝箱全屏按钮","Path"=>"UIRoot/NormalLayer/UIEpitaphView/BG"],
35=>["ID"=>35,"Desc"=>"哨站2锁按钮","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_1/img_Lock"],
36=>["ID"=>36,"Desc"=>"哨站2区域","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_1"],
37=>["ID"=>37,"Desc"=>"加速付费确认按钮","Path"=>"UIRoot/PopUpLayer/UIPureTextPopUpView/Panel/BtnGroup/UIBuyButton"],
38=>["ID"=>38,"Desc"=>"迷雾信息跳转商店界面","Path"=>"UIRoot/PopUpLayer/UIPopulationPopUpView/Panel/Content/Part_1/btn_Go"],
39=>["ID"=>39,"Desc"=>"龙蛋道具1001","Path"=>"UIRoot/NormalLayer/UIShopView_new/Panel/TabScrollPanel_3/Viewport/Content/6012"],
40=>["ID"=>40,"Desc"=>"挑战关卡时间进度条","Path"=>"UIRoot/NormalLayer/UITimeLevelCountDownView/Panel/Up/time_Slider"],
41=>["ID"=>41,"Desc"=>"挑战关卡商店","Path"=>"UIRoot/NormalLayer/UILevelView/Panel/RightDown/btn_Shop"],
42=>["ID"=>42,"Desc"=>"挑战关卡商品10002","Path"=>"UIRoot/NormalLayer/UIShopView_new/Panel/TabScrollPanel_8/Viewport/Content/10003"],
43=>["ID"=>43,"Desc"=>"挑战关卡结算界面双倍按钮","Path"=>"UIRoot/NormalLayer/UITimeLevelRewardView/Panel/BtnContent/DoubleReward"],
44=>["ID"=>44,"Desc"=>"关卡卷轴星星进度区域【五边形整体】","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/RewardContent/Bg"],
45=>["ID"=>45,"Desc"=>"哨站3锁按钮","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_2/img_Lock"],
46=>["ID"=>46,"Desc"=>"哨站3区域","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_2"],
47=>["ID"=>47,"Desc"=>"主UI上英雄界面入口","Path"=>"UIRoot/MainLayer/UIHomelandView/Panel/Content_RB/btn_Hero"],
48=>["ID"=>48,"Desc"=>"Sea活动界面积分奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Sea(Clone)/Points"],
49=>["ID"=>49,"Desc"=>"1号活动活动界面积分奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Default(Clone)/Points"],
50=>["ID"=>50,"Desc"=>"2号活动活动界面积分奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Ice(Clone)/Points"],
51=>["ID"=>51,"Desc"=>"童话镇活动界面积分奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Fairytales(Clone)/Points"],
52=>["ID"=>52,"Desc"=>"猫咪活动界面积分奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Meow(Clone)/Points"],
53=>["ID"=>53,"Desc"=>"主城UI每日任务按钮","Path"=>"UIRoot/MainLayer/UIDailyTaskGateView/Panel/LeftUp/btn_DailyTask"],
54=>["ID"=>54,"Desc"=>"每日任务界面任务词条区域","Path"=>"UIRoot/NormalLayer/UIDailyTaskView/Panel/Img_Bg/DailyTasks/Scroll View/Viewport/Content/Item(Clone)"],
55=>["ID"=>55,"Desc"=>"每日任务1号日完结奖励区域","Path"=>"UIRoot/NormalLayer/UIDailyTaskView/Panel/Img_Bg/FiveTimesRewardBg/Rewards/RewardItem_0"],
56=>["ID"=>56,"Desc"=>"千年活动界面积分奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Egypt(Clone)/Points"],
57=>["ID"=>57,"Desc"=>"西部活动积分面板奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Westworld(Clone)/Points"],
58=>["ID"=>58,"Desc"=>"旅游活动积分面板奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Sakura(Clone)/Points"],
59=>["ID"=>59,"Desc"=>"哨站3锁按钮","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_3/img_Lock"],
60=>["ID"=>60,"Desc"=>"哨站3区域","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_3"],
61=>["ID"=>61,"Desc"=>"玩具活动积分面板奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Doll(Clone)/Points"],
62=>["ID"=>62,"Desc"=>"海滩活动积分面板奖励UI","Path"=>"UIRoot/MainLayer/UIActivityMainView/Panel/ActivityMainParent/ActivityMain_Holiday(Clone)/Points"],
63=>["ID"=>63,"Desc"=>"每日任务关闭按钮","Path"=>"UIRoot/NormalLayer/UIDailyTaskView/Panel/Img_Bg/btn_Close"],
64=>["ID"=>64,"Desc"=>"主城UI任务ICon按钮","Path"=>"UIRoot/MainLayer/UINewHomeTaskItemGateView/Panel/Left/Scroll View/Viewport/Content/TaskItem329902/MsgPanel/Bg"],
65=>["ID"=>65,"Desc"=>"主城UI商店ICon按钮","Path"=>"UIRoot/MainLayer/UIHeroInstanceView/Panel/Content_RB/btn_Shop"],
66=>["ID"=>66,"Desc"=>"每日任务寻找按钮UI","Path"=>"UIRoot/NormalLayer/UINewHomeTaskItemMsgView/Panel/TaskMsg/btn_Find"],
67=>["ID"=>67,"Desc"=>"积分宝箱免费按钮UI","Path"=>"UIRoot/NormalLayer/UIShopView_new/Panel/TabScrollPanel_12/Viewport/Content/13301/Content/UIBuyButton"],
68=>["ID"=>68,"Desc"=>"商店关闭按钮UI","Path"=>"UIRoot/NormalLayer/UIShopView_new/Panel/btn_Close"],
70=>["ID"=>70,"Desc"=>"家园跳转集合入口按钮","Path"=>"UIRoot/MainLayer/UIHeroInstanceView/Panel/Content_RB/btn_WorldMap"],
71=>["ID"=>71,"Desc"=>"第二家园页签按钮","Path"=>"UIRoot/PopUpLayer/UIEntranceView/Panel/CardPanel/Scroll View/Viewport/Content/SecondHomeCard/Bg/ButtonPanel/btn_Go"],
72=>["ID"=>72,"Desc"=>"喂食奖励按钮","Path"=>"UIRoot/MainLayer/UIFeedGiftBtnView/Panel/Anchor/GetBtn"],
73=>["ID"=>73,"Desc"=>"喂食奖励界面关闭区域","Path"=>"UIRoot/NormalLayer/UIFeedGetGiftView/Panel"],
74=>["ID"=>74,"Desc"=>"交易系统图标按钮","Path"=>"UIRoot/MainLayer/UIExchangeBtnView/Panel/Anchor/Btn"],
75=>["ID"=>75,"Desc"=>"交易系统界面左边生物区域","Path"=>"UIRoot/NormalLayer/UIExchangeView/Panel/Main/LeftScroll/Scroll View/Viewport/Content/0/Btn"],
76=>["ID"=>76,"Desc"=>"交易系统界面右边第一个生物区域","Path"=>"UIRoot/NormalLayer/UIExchangeView/Panel/Main/RightScroll/Scroll View/Viewport/Content/0/Btn"],
77=>["ID"=>77,"Desc"=>"交易按钮","Path"=>"UIRoot/NormalLayer/UIExchangeView/Panel/Main/RightScroll/RightSelected/ExchangeBtn"],
78=>["ID"=>78,"Desc"=>"宠物乐园商店图标路径","Path"=>"UIRoot/MainLayer/UIPetsEdenView/Panel/Content_RB/btn_Shop"],
79=>["ID"=>79,"Desc"=>"背包图标按钮","Path"=>"UIRoot/MainLayer/UIPetsBackPackEntryView/Panel/Anchor/BackpackBtn"],
90=>["ID"=>90,"Desc"=>"体力加号按路径","Path"=>"UIRoot/MainLayer/UIHeroCoinBarView/Panel/WorkPhy/Button"],
91=>["ID"=>91,"Desc"=>"商店免费礼包按钮路径","Path"=>"UIRoot/NormalLayer/UIWorkerPhysicalShopView/Panel/img_Bg/CardsPanel/GiftPackCard/img_Bg/img_Play"],
);
?>