<?php
return array(
1=>["ID"=>1,"NameText"=>"创世神之梦","Describe"=>"放不下的奖励会被暂时收进创世神的梦中等待被唤醒。","NameImageLocation"=>"top","NameImage"=>"","StandbyImage"=>"ui_argb_common_lianjijiangli","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_01","Remark"=>"普通泡泡","NameTextKey"=>"泡泡名称1","DescribeKey"=>"泡泡描述1"],
2=>["ID"=>2,"NameText"=>"宝箱美梦","Describe"=>"创世神的梦中藏着无尽的财宝。","NameImageLocation"=>"top","NameImage"=>"","StandbyImage"=>"ui_argb_common_putong","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_01","Remark"=>"等级宝箱","NameTextKey"=>"泡泡名称2","DescribeKey"=>"泡泡描述2"],
3=>["ID"=>3,"NameText"=>"奖励之梦","Describe"=>"创世神的梦中藏着无尽的财宝。","NameImageLocation"=>"top","NameImage"=>"ui_argb_common_guanqiajiangli","StandbyImage"=>"ui_argb_common_guanqia","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_03","Remark"=>"关卡奖励","NameTextKey"=>"泡泡名称3","DescribeKey"=>"泡泡描述3"],
4=>["ID"=>4,"NameText"=>"原生梦境","Describe"=>"失落梦境的孤魂在被遗忘的土地上游荡。","NameImageLocation"=>"top","NameImage"=>"","StandbyImage"=>"ui_argb_common_dikuaipao","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"bubble_massif","BirthEffectLocation"=>"center","BirthEffect"=>"","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_02","Remark"=>"地块默认","NameTextKey"=>"泡泡名称4","DescribeKey"=>"泡泡描述4"],
5=>["ID"=>5,"NameText"=>"富庶美梦","Describe"=>"向创世神大量进贡得到的奖励。","NameImageLocation"=>"top","NameImage"=>"ui_argb_common_lianji","StandbyImage"=>"ui_argb_common_putong","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_04","Remark"=>"连击泡泡1","NameTextKey"=>"泡泡名称5","DescribeKey"=>"泡泡描述5"],
6=>["ID"=>6,"NameText"=>"丰收美梦","Describe"=>"向创世神大量进贡得到的奖励。","NameImageLocation"=>"top","NameImage"=>"ui_argb_common_lianji","StandbyImage"=>"ui_argb_common_putong","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_04","Remark"=>"连击泡泡2","NameTextKey"=>"泡泡名称6","DescribeKey"=>"泡泡描述6"],
7=>["ID"=>7,"NameText"=>"壮丽美梦","Describe"=>"给虔诚信徒的厚礼。","NameImageLocation"=>"top","NameImage"=>"ui_argb_common_lianji","StandbyImage"=>"ui_argb_common_putong","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_04","Remark"=>"连击泡泡3","NameTextKey"=>"泡泡名称7","DescribeKey"=>"泡泡描述7"],
8=>["ID"=>8,"NameText"=>"无尽美梦","Describe"=>"创世神的恩典。","NameImageLocation"=>"top","NameImage"=>"ui_argb_common_lianji","StandbyImage"=>"ui_argb_common_putong","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_04","Remark"=>"连击泡泡4","NameTextKey"=>"泡泡名称8","DescribeKey"=>"泡泡描述8"],
9=>["ID"=>9,"NameText"=>"排名之梦","Describe"=>"创世神奖励给在闯关排行中获得荣耀的人。","NameImageLocation"=>"top","NameImage"=>"ui_argb_common_guanqiajiangli","StandbyImage"=>"ui_argb_common_guanqia","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_03","Remark"=>"排名奖励","NameTextKey"=>"泡泡名称9","DescribeKey"=>"泡泡描述9"],
10=>["ID"=>10,"NameText"=>"奖励之梦","Describe"=>"创世神的梦中藏着无尽的财宝。","NameImageLocation"=>"","NameImage"=>"","StandbyImage"=>"ui_argb_common_teshupaopao","PreviewQuantity"=>1,"PreviewLocation"=>"","StandbyEffectLocation"=>"","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"shop_special_bubble","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_03","Remark"=>"购买表现","NameTextKey"=>"泡泡名称3","DescribeKey"=>"泡泡描述3"],
11=>["ID"=>11,"NameText"=>"赛季奖励","Describe"=>" 点击获取赛季奖励！","NameImageLocation"=>"top","NameImage"=>"ui_argb_common_saijijiangli","StandbyImage"=>"ui_argb_common_teshupaopao","PreviewQuantity"=>1,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_04","Remark"=>"赛季奖励","NameTextKey"=>"泡泡名称10","DescribeKey"=>"泡泡描述10"],
12=>["ID"=>12,"NameText"=>"新家园泡泡","Describe"=>"","NameImageLocation"=>"","NameImage"=>"","StandbyImage"=>"ui_argb_common_bubble","PreviewQuantity"=>5,"PreviewLocation"=>"center","StandbyEffectLocation"=>"center","StandbyEffect"=>"","BirthEffectLocation"=>"center","BirthEffect"=>"bubble_birth","ImageOpenEffectLocation"=>"center","ImageOpenEffect"=>"bubble_open","OpenSound"=>"sound_openbubble_04","Remark"=>"新家园","NameTextKey"=>"泡泡名称9","DescribeKey"=>"泡泡描述9"],
);
?>