<?php
return array(
1=>["Id"=>1,"Type"=>1,"Level"=>0,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_cards_xpizhi0","BangsAssetName"=>"ui_argb_cards_xlv0","StreamerAssetName"=>"ui_argb_common_pjtiao0","TextColor"=>"ffffffff","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
2=>["Id"=>2,"Type"=>1,"Level"=>1,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_cards_xpizhi1","BangsAssetName"=>"ui_argb_cards_xlv1","StreamerAssetName"=>"ui_argb_common_pjtiao1","TextColor"=>"406d3aff","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
3=>["Id"=>3,"Type"=>1,"Level"=>2,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_cards_xpizhi2","BangsAssetName"=>"ui_argb_cards_xlv2","StreamerAssetName"=>"ui_argb_common_pjtiao2","TextColor"=>"05686dff","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
4=>["Id"=>4,"Type"=>1,"Level"=>3,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_cards_xpizhi3","BangsAssetName"=>"ui_argb_cards_xlv3","StreamerAssetName"=>"ui_argb_common_pjtiao3","TextColor"=>"744dafff","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
5=>["Id"=>5,"Type"=>1,"Level"=>4,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_cards_xpizhi4","BangsAssetName"=>"ui_argb_cards_xlv4","StreamerAssetName"=>"ui_argb_common_pjtiao4","TextColor"=>"ac5b1fff","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
6=>["Id"=>6,"Type"=>1,"Level"=>5,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_cards_xpizhi5","BangsAssetName"=>"ui_argb_cards_xlv5","StreamerAssetName"=>"ui_argb_common_pjtiao5","TextColor"=>"ac5b1fff","SpecialAssetName1"=>"ui_qualitybox_small","SpecialAssetName2"=>"ui_qualitybox_smallbig","SpecialAssetName3"=>"ui_qualitybox_middle","SpecialAssetName4"=>"ui_qualitybox_big"],
7=>["Id"=>7,"Type"=>2,"Level"=>1,"IconAssetName"=>"ui_argb_common_db11","FrameAssetName"=>"","BangsAssetName"=>"","StreamerAssetName"=>"","TextColor"=>"","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
8=>["Id"=>8,"Type"=>2,"Level"=>2,"IconAssetName"=>"ui_argb_common_db12","FrameAssetName"=>"","BangsAssetName"=>"","StreamerAssetName"=>"","TextColor"=>"","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
9=>["Id"=>9,"Type"=>2,"Level"=>3,"IconAssetName"=>"ui_argb_common_db13","FrameAssetName"=>"","BangsAssetName"=>"","StreamerAssetName"=>"","TextColor"=>"","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
10=>["Id"=>10,"Type"=>3,"Level"=>1,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_Petbag_tc9","BangsAssetName"=>"","StreamerAssetName"=>"","TextColor"=>"","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
11=>["Id"=>11,"Type"=>3,"Level"=>2,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_Petbag_tc8","BangsAssetName"=>"","StreamerAssetName"=>"","TextColor"=>"","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
12=>["Id"=>12,"Type"=>3,"Level"=>3,"IconAssetName"=>"","FrameAssetName"=>"ui_argb_Petbag_tc7","BangsAssetName"=>"","StreamerAssetName"=>"","TextColor"=>"","SpecialAssetName1"=>"","SpecialAssetName2"=>"","SpecialAssetName3"=>"","SpecialAssetName4"=>""],
);
?>