<?php
return array(
1=>["ID"=>1,"Desc"=>"哨站任务1弹窗【废弃】","Path"=>"UIRoot/MainLayer/UIOutpostView/Panel/LeftMiddle/Task_0"],
2=>["ID"=>2,"Desc"=>"哨站任务1弹窗【废弃】","Path"=>"UIRoot/PopUpLayer/UIOutPostTaskPanelPopUpView/Panel/img_Bg/Content/img_InfoBg"],
3=>["ID"=>3,"Desc"=>"哨站左下角挑战关卡按钮","Path"=>"UIRoot/MainLayer/UIOutpostView/Panel/LeftDown/img_btnLevelSelection/btn_LevelSelectionView/icon"],
4=>["ID"=>4,"Desc"=>"关卡列表中，关卡100区域","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_0/NormalLevelBtn(Clone)/btn_Level"],
5=>["ID"=>5,"Desc"=>"关卡列表中，关卡102区域","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_1/NormalLevelBtn(Clone)/btn_Level"],
6=>["ID"=>6,"Desc"=>"关卡列表中，关卡103区域","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_2/NormalLevelBtn(Clone)/btn_Level"],
7=>["ID"=>7,"Desc"=>"关卡信息界面，挑战按钮","Path"=>"UIRoot/NormalLayer/UILevelMsgView/Panel/Down/btn_Begin"],
8=>["ID"=>8,"Desc"=>"哨站界面返回按钮","Path"=>"UIRoot/MainLayer/UIOutpostView/Panel/RightDown/img_btnWorldMap/btn_ToWorldMap/icon"],
9=>["ID"=>9,"Desc"=>"世界地图中哨站奖励区域【包括星星和倒计时时间】","Path"=>"UIRoot/MainLayer/UIWorldMapView/Panel/OutPostReward_0/BG/ProgressBar/CountDownPanel/IconObj/img_Icon"],
10=>["ID"=>10,"Desc"=>"前往家园按钮","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/img_btnHomaland/btn_Homeland"],
11=>["ID"=>11,"Desc"=>"关卡主UI，任务目标区域","Path"=>"UIRoot/NormalLayer/UILevelView/Panel/UpMiddle/img_Bg"],
12=>["ID"=>12,"Desc"=>"","Path"=>""],
13=>["ID"=>13,"Desc"=>"","Path"=>""],
14=>["ID"=>14,"Desc"=>"家园商店按钮","Path"=>"UIRoot/MainLayer/UIHomelandView/Panel/RightMiddle/btn_Shop/img_Shop"],
15=>["ID"=>15,"Desc"=>"关卡任务之星按钮，任一","Path"=>"UIRoot/MainLayer/UITaskView/Panel/LeftMiddle/Task_0"],
16=>["ID"=>16,"Desc"=>"屏幕锁定按钮","Path"=>"UIRoot/NormalLayer/UILevelView/Panel/RightDown/LockCamera/btn_Lock"],
17=>["ID"=>17,"Desc"=>"家园任务区域","Path"=>"UIRoot/MainLayer/UITaskView/Panel/LeftMiddle/Task_0"],
18=>["ID"=>18,"Desc"=>"建筑商店页签","Path"=>"UIRoot/NormalLayer/UIShopView/Panel/ToggleGroups/toggle_3"],
19=>["ID"=>19,"Desc"=>"金币库道具11901","Path"=>"UIRoot/NormalLayer/UIShopView/Panel/Down/img_bg/ShopContent_3/Viewport/Content/11901/Empty"],
20=>["ID"=>20,"Desc"=>"家园返回哨站按钮","Path"=>"UIRoot/MainLayer/UIHomelandView/Panel/RightMiddle/btn_Map/icon"],
21=>["ID"=>21,"Desc"=>"哨站1区域","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_0"],
22=>["ID"=>22,"Desc"=>"图书馆道具12001","Path"=>"UIRoot/NormalLayer/UIShopView/Panel/Down/img_bg/ShopContent_3/Viewport/Content/12001/Empty"],
23=>["ID"=>23,"Desc"=>"英雄升级页签按钮","Path"=>"UIRoot/NormalLayer/UIHeroView/Panel/Hero/Info/Upgrade"],
24=>["ID"=>24,"Desc"=>"英雄技能1区域","Path"=>"UIRoot/NormalLayer/UIHeroView/Panel/Hero/Info/BG/DetailsPanel/Skill"],
25=>["ID"=>25,"Desc"=>"英雄升级按钮","Path"=>"UIRoot/NormalLayer/UIHeroView/Panel/Hero/Display/Upgrad"],
26=>["ID"=>26,"Desc"=>"订单内容区域","Path"=>"UIRoot/NormalLayer/UIHeroView/Panel/Hero/Info/BG/UpgradePanel/Receipts/Scroll View/Viewport"],
27=>["ID"=>27,"Desc"=>"选关界面全屏关闭按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/BG"],
28=>["ID"=>28,"Desc"=>"UI宝箱按钮","Path"=>"UIRoot/MainLayer/UIEpitaphBarView/Panel/EpitaphView/EpitaphViews"],
29=>["ID"=>29,"Desc"=>"UI宝箱界面宝箱1开启按钮","Path"=>"UIRoot/NormalLayer/UIEpitaphView/Panel/Down/EpitaphItem_0/img_Bg/ItemBtns/Three/btn_UnLocked"],
30=>["ID"=>30,"Desc"=>"祭坛信息“操作按钮”","Path"=>"UIRoot/MainLayer/UIDetailsBarView/Panel/img_Mask/img_FlexBg/BtnContent/btn_Update"],
31=>["ID"=>31,"Desc"=>"关卡列表中，关卡104按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_3/NormalLevelBtn(Clone)/btn_Level"],
32=>["ID"=>32,"Desc"=>"关卡列表中，关卡105按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_4/NormalLevelBtn(Clone)/btn_Level"],
33=>["ID"=>33,"Desc"=>"关卡列表中，关卡106按钮","Path"=>"UIRoot/NormalLayer/UISelectionLevelView/Panel/BG/Middle/OutPost_View_0/Viewport/Content/Btns/Item_0/LevelBtns/levelBtn_5/NormalLevelBtn(Clone)/btn_Level"],
34=>["ID"=>34,"Desc"=>"时间宝箱全屏按钮","Path"=>"UIRoot/NormalLayer/UIEpitaphView/BG"],
35=>["ID"=>35,"Desc"=>"哨站2锁按钮","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_1/img_Lock"],
36=>["ID"=>36,"Desc"=>"哨站2区域","Path"=>"UIRoot/PopUpLayer/UIWorldMapView/Panel/Scroll View/Viewport/Content/Button_1"],
37=>["ID"=>37,"Desc"=>"加速付费确认按钮","Path"=>"UIRoot/PopUpLayer/UIPureTextPopUpView/Panel/BtnGroup/btn_Buy"],
38=>["ID"=>38,"Desc"=>"迷雾信息跳转商店界面","Path"=>"UIRoot/PopUpLayer/UIPopulationPopUpView/Panel/Content/Part_1/btn_Go"],
39=>["ID"=>39,"Desc"=>"龙蛋道具1001","Path"=>"UIRoot/NormalLayer/UIShopView/Panel/Down/img_bg/ShopContent_1/Viewport/Content/1001/Empty"],
40=>["ID"=>40,"Desc"=>"挑战关卡时间进度条","Path"=>"UIRoot/NormalLayer/UITimeLevelCountDownView/Panel/Up/time_Slider"],
41=>["ID"=>41,"Desc"=>"挑战关卡商店","Path"=>"UIRoot/NormalLayer/UILevelView/Panel/RightDown/btn_Shop"],
42=>["ID"=>42,"Desc"=>"挑战关卡商品10002","Path"=>"UIRoot/NormalLayer/UIShopView/Panel/Down/img_bg/ShopContent_5/Viewport/Content/10002/Empty"],
43=>["ID"=>43,"Desc"=>"挑战关卡结算界面双倍按钮","Path"=>"UIRoot/NormalLayer/UITimeLevelRewardView/Panel/BtnContent/DoubleReward"],
);
?>