---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/6/1 15:23
---
---工厂加速券礼包
local LessItemCount = require("Game.System.Gift.GiftPrecondition.GiftPreconditionLessItemCount")
local Base = require("Game.System.Gift.GiftInstance.GiftInstanceBase")
---@class GiftInstance_430 : GiftInstanceBase
local GiftInstance_430 = class(Base, "GiftInstance_430")

function GiftInstance_430:ctor(config)
    GiftInstance_430.super.ctor(self, config)

    self.checkCount = 5

    local lessItemCount = LessItemCount.new()
    lessItemCount:SetCheckParam(ItemId.FactorySpeedUp, self.checkCount)
    self.preconditionAry[#self.preconditionAry + 1] = lessItemCount
end

function GiftInstance_430:AutoOpenEvent()
    return {}
end

function GiftInstance_430:GetPanelName()
    return "GiftResourcePanel"
end

function GiftInstance_430:GetPopFlag()
    return {}
end

function GiftInstance_430:GetUIConfig()
    return {Localization = {localization_title = "UI_factory_speedup_special", localization_desc = "UI_factory_speedup_special_desc"}}
end

return GiftInstance_430