---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/6/1 16:10
---
---委托加速券礼包
local Base = require("Game.System.Gift.GiftInstance.GiftInstanceBase")
---@class GiftInstance_420 : GiftInstanceBase
local GiftInstance_420 = class(Base, "GiftInstance_420")

function GiftInstance_420:ctor(config)
    GiftInstance_420.super.ctor(self, config)
end

function GiftInstance_420:AutoOpenEvent()
    return {}
end

function GiftInstance_420:GetPanelName()
    return "GiftResourcePanel"
end

function GiftInstance_420:GetPopFlag()
    return {}
end

function GiftInstance_420:GetUIConfig()
    return {Localization = {localization_title = "UI_explore_help_special"}}
end

return GiftInstance_420