---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DKSS.
--- DateTime: 2022/6/1 14:34
---
---棒棒糖礼包2
local Base = require("Game.System.Gift.GiftInstance.GiftInstanceBase")
---@class GiftInstance_451 : GiftInstanceBase
local GiftInstance_451 = class(Base, "GiftInstance_451")

function GiftInstance_451:ctor(config)
    GiftInstance_451.super.ctor(self, config)

    local userGroup = Base.PreconditionUserGroup.new({"3", "5", "6", "8"})
    local trigger450 = Base.PreconditionTriggerGift.new(450)
    local trigger451 = Base.PreconditionTriggerGift.new(451)
    local trigger452 = Base.PreconditionTriggerGift.new(452)
    local firstCheck = Base.PreconditionAND.new({userGroup,     --初始AEO，中R展示5.99档位
                                                 Base.PreconditionNO.new(trigger450),
                                                 Base.PreconditionNO.new(trigger451),
                                                 Base.PreconditionNO.new(trigger452)})
    local Bought451 = Base.PreconditionBoughtGift.new(451, false)  --购买了451档次（452 config优先级更高）
    local Bought450 = Base.PreconditionBoughtGift.new(450, true)
    local upCheck = Base.PreconditionAND.new({Bought450, Base.PreconditionNO.new(trigger451)})  --购买了450档位，还没触发过451档位，尝试触发451档位
    local fixCheck = Base.PreconditionAND.new({trigger452, Base.PreconditionNO.new(trigger451)})  --触发了452，没出发450，降档
    self:AddPrecondition(Base.PreconditionOR.new({firstCheck, Bought451, upCheck, fixCheck}))
end

function GiftInstance_451:GetPanelName()
    return "GiftResourcePanel"
end

function GiftInstance_451:AutoOpenEvent()
    return {}
end

function GiftInstance_451:GetUIConfig()
    return {Localization = {localization_title = "UI_gift_key_title", localization_desc = "UI_gift_key_desc", text_buy = "UI_gift_buy"}}
end

return GiftInstance_451